# Base image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt /app/

# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the training script (train.py) to the working directory
COPY train.py /app/

# Run the training script that generates the model
CMD ["python", "train.py"]
